name: Build Plugins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      plugin:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Plugins
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Detect changed files
        if: github.event_name != 'workflow_dispatch'
        id: changed-files
        uses: tj-actions/changed-files@v24
      
      - name: Build updated plugins
        id: build
        # crappy workaround for manual run
        run: node .github/workflows/build.js ${{ steps.changed-files.outputs.all_changed_files || format('{0}/src', github.event.inputs.plugin) }}

      - name: Push changes
        if: steps.build.outputs.built == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.build.outputs.message }}
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

