name: Check Pull Request

on:
  pull-request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Detect changed files
        id: changed-files
        uses: tj-actions/changed-files@v24

      - name: Build updated plugins
        run: node .github/workflows/build.js ${{ steps.changed-files.outputs.all_changed_files }}
